version: "3.7"


networks:
  couchbase-net:
    name: couchbase-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24


services:

  couchbase-server:
    image: gsi/couchbase-server:6.5
    container_name: couchbase-server
    hostname: couchbase-server
    volumes:
        - /home/dexter/Documents/GSI/CouchBase/couchbase-tutorials:/home/couchbase-tutorials
    restart: always
    networks:
      couchbase-net:
        ipv4_address: 192.168.1.10